[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
blueshift_anchor_flash_loan = "6UrqmN5T95eyF51XfWcnHNoQq7HBHjLn8onRd8iiEa3d"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
